import Head from 'next/head'
import Image from 'next/image'
import LaunchList from '../components/LaunchList';
import Container from '@material-ui/core/Container';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" />
      </Head>
      <Container maxWidth="lg">
        <LaunchList />
      </Container>
    </div>
  )
}
